default:
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  services:
  - name: gcr.io/pluralsh/docker:19.03.13-dind
    alias: docker
  before_script:
  - until docker info; do sleep 1; done
  - gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
  - gcloud auth configure-docker -q
  - docker login -u mguarino46@gmail.com -p $PLURAL_ACCESS_TOKEN dkr.plural.sh

  retry:
    max: 2
    when:
    - runner_system_failure

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
- push

push-external-dns:
  stage: push
  script:
  - docker build --build-arg ARCH="amd64" -t gcr.io/pluralsh/external-dns:v0.7.6 -t dkr.plural.sh/bootstrap/external-dns:v0.7.6 .
  - docker push gcr.io/pluralsh/external-dns:v0.7.6
  - docker push dkr.plural.sh/bootstrap/external-dns:v0.7.6
